sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wuwei
  #阿里云OSS
  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: java-wuwei
      region: cn-beijing
  redis:
    host: localhost
    port: 6379
    database: 2
  wechat:
    appid: wxabc0f9330ab4138b
    secret: 91421eb91239e66f6b111d06e9ac65af